### PR TITLE
Add authorship to Cookbook template

### PR DESCRIPTION
**Pull request by brian-rose**

### CODE REVIEW

**Comment by brian-rose** [comment]
This PR addresses part of https://github.com/ProjectPythiaCookbooks/projectpythiacookbooks.github.io/issues/15 by adding acknowledgement of authorship to the Cookbook template.

The idea is that each Cookbook will have one or more "primary" authors credited with the science content. This part is manually added to the README.

In addition, I'm using a neat tool that dynamically adds an image with ALL contributors to the repository. Clicking on this image will bring you to the contributors graph page for the repository where you can see all the details.

This is a way to ensure that all contributors are visibly acknowledged on the rendered Cookbook itself, not just in the source repo.

**Review by clyne — APPROVED** [review]
Looks great, @brian-rose !

**Comment by ktyle** [comment]
This looks great! I notice though that "dependabot" is included in the list of contributors ... can bots such as that be excluded from the contributor list?

**Comment by brian-rose** [comment]
> This looks great! I notice though that "dependabot" is included in the list of contributors ... can bots such as that be excluded from the contributor list?

I think that would be better, but I don't know of an easy way to make it work. I opened an issue on the tool I'm using to generate the contributors image:
https://github.com/lacolaco/contributors-img/issues/1175

**Comment by ktyle** [comment]
Understood ... I'm happy to give credit to the bots in the meantime!

**Review by ktyle — APPROVED** [review]

**Pull request merged**
